### ISSUE TITLE
Will irgendwie nicht funktionieren.

### ISSUE THREAD

**Issue by RalMakadonia** [robotfreak/dfhacks#1]
Guten tag!

ich habe alles nach dem Buch her aufgebaut, doch bekomme ich die IR-Lichtschranke nicht hin. 
Wenn ich das Programm mithilfe von TimeOne.h benutze (gepflegte Variante auf https://github.com/PaulStoffregen/TimerOne ), zeigt mir die Konsole nur "IR" an. Nicht jedoch den vollen Text "IR Light barrier test v0.1".

Wenn irRcvPin == LOW ist, sollte die IR-Diode direkt auf den Sensor drauf halten, bzw. das licht von einer Quelle auf den Sensor reflektiert werden oder nicht?
Ohne Timer.One.h habe ich es zwar hinbekommen, aber nicht reproduzierbar. Ich bin mir da gerade nicht sicher warum.

Mit freundlichen Grüßen
Sebastian Ocampo

**Comment by robotfreak** [comment]
Hallo Sebastian,

danke für den Hinweis. Ich denke das Problem ist mit dem aktualisierten Sketch gefixed.

 Die ISR Routine dauerte wohl etwas zu lange.  Statt den Pin einzulesen und zu togglen, wird jetzt nur eine Variable getoggeld.
Noch ein Tip Die Reichweite des Senders ist leider nicht sehr hoch (wenige cm). Mit einer handelsüblichen Fernbedienung als Sender erreicht man sehr viel bessere Werte (einige m). Man muss nur eine Taste der Fernbedienung festklemmen um im Dauerbetrieb zu senden.

LG Peter
